# Copyright 2023-2026 Timo Röhling <timo@gaussglocke.de>
# SPDX-License-Identifier: FSFAP
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
#
name: CI (BSD)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y cmake git gmake libconfuse check sqlite3 hiredis
          run: |
            mkdir _build
            cd _build
            cmake .. -DDEVELOPER_BUILD=ON -DWITH_SQLITE=ON -DWITH_REDIS=ON
            cmake --build . --verbose
            ctest --verbose
  openbsd:
    runs-on: ubuntu-latest
    name: OpenBSD
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg_add cmake git gmake libconfuse check sqlite3 libhiredis
          run: |
            mkdir _build
            cd _build
            cmake .. -DDEVELOPER_BUILD=ON -DWITH_SQLITE=ON -DWITH_REDIS=ON
            cmake --build . --verbose
            ctest --verbose
  netbsd:
    runs-on: ubuntu-latest
    name: NetBSD
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/netbsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg_add cmake git gmake libconfuse check sqlite3 libhiredis
          run: |
            mkdir _build
            cd _build
            cmake .. -DDEVELOPER_BUILD=ON -DWITH_SQLITE=ON -DWITH_REDIS=ON
            cmake --build . --verbose
            ctest --verbose
  macos:
    runs-on: macos-latest
    name: MacOS
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install gcc python cmake git confuse check sqlite hiredis
      - name: Build PostSRSd
        run: |
          mkdir _build
          cd _build
          cmake .. -DDEVELOPER_BUILD=ON -DWITH_SQLITE=ON -DWITH_REDIS=ON
          cmake --build . --verbose
      - name: Run tests
        run: |
          cd _build
          ctest --verbose
