# Copyright 2023 Timo Röhling <timo@gaussglocke.de>
# SPDX-License-Identifier: FSFAP
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
#
name: CI on non-Linux systems
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y cmake git gmake libconfuse sqlite3 hiredis
          run: |
            mkdir _build
            cd _build
            cmake .. -DDEVELOPER_BUILD=ON -DWITH_SQLITE=ON -DWITH_REDIS=ON && gmake VERBOSE=ON && ctest --verbose
  openbsd:
    runs-on: ubuntu-latest
    name: OpenBSD
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg_add cmake git gmake libconfuse sqlite3 libhiredis
          run: |
            mkdir _build
            cd _build
            cmake .. -DDEVELOPER_BUILD=ON -DWITH_SQLITE=ON -DWITH_REDIS=ON && gmake VERBOSE=ON && ctest --verbose
  solrais:
    runs-on: ubuntu-latest
    name: Solaris
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/solaris-vm@v1
        with:
          usesh: true
          prepare: |
            curl -fso /root/cmake.sh https://github.com/Kitware/CMake/releases/download/v4.4.0/cmake-4.4.0-sunos-x86_64.sh
            chmod +x /root/cmake.sh
            /root/cmake.sh --skip-license --prefix=/usr/local
            pkgutil -y -i curl git gmake libconfuse_dev libsqlite3_dev
          run: |
            mkdir _build
            cd _build
            cmake .. -DDEVELOPER_BUILD=ON -DWITH_SQLITE=ON && gmake VERBOSE=ON && ctest --verbose
